-- Analytics Table
create table if not exists analytics_logs (
    id bigint generated by default as identity primary key,
    path text not null,
    referrer text,
    ip_hash text, -- Anonymized IP or Session ID
    user_agent text,
    device_type text, -- 'mobile', 'desktop', 'tablet'
    country text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for fast dashboard queries
create index if not exists idx_analytics_created_at on analytics_logs(created_at);
create index if not exists idx_analytics_path on analytics_logs(path);

-- RLS Policies
alter table analytics_logs enable row level security;

-- Allow public to insert logs (logging page views)
create policy "Allow public insert"
on analytics_logs for insert
to public
with check (true);

-- Allow admins to view logs (via service role or if we had admin headers)
-- For now, we mainly access this via server component or service role
create policy "Allow service role select"
on analytics_logs for select
to service_role
using (true);

-- Optional: Clean up old logs (e.g., older than 90 days)
-- This would be a pg_cron job in a real production environment
